name: digger

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - environments/**
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')

jobs:
  digger-account-a:
    uses: ./.github/workflows/digger-shared.yml
    with:
      aws_profile_name: account-a
      digger_filename: account_a.yml
      terraform_version: 1.8.4
    secrets:
      AWS_IAM_ROLE_ARN: arn:aws:iam::000000000001:role/terraform # from environments/account_a/cicd.tf

  digger-account-b:
    uses: ./.github/workflows/digger-shared.yml
    with:
      aws_profile_name: account-b
      digger_filename: account_b.yml
      terraform_version: 1.8.4
    secrets:
      AWS_IAM_ROLE_ARN: arn:aws:iam::000000000002:role/terraform # from environments/account_b/cicd.tf
